"use client";
import { useEffect,useState } from "react";
import { FaCode,FaPlus,FaTrash } from "react-icons/fa";
type Row={login:string;added_by:string;created_at:string};
export default function DeveloperManagementPanel(){const [rows,setRows]=useState<Row[]>([]),[login,setLogin]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
async function load(){const r=await fetch("/api/owner/developers");const d=await r.json();if(r.ok)setRows(d);else setError(d.error||"Gagal memuat developer")}
useEffect(()=>{load()},[]); async function add(e:React.FormEvent){e.preventDefault();if(!login.trim())return;setBusy(true);try{const r=await fetch("/api/owner/developers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({login:login.trim()})});const d=await r.json();if(!r.ok)throw Error(d.error);setLogin("");load()}catch(e:any){alert(e.message)}finally{setBusy(false)}}
async function remove(x:string){if(!confirm(`Cabut role developer dari "${x}"?`))return;setBusy(true);try{const r=await fetch(`/api/owner/developers/${encodeURIComponent(x)}`,{method:"DELETE"});const d=await r.json();if(!r.ok)throw Error(d.error);load()}catch(e:any){alert(e.message)}finally{setBusy(false)}}
return <div className="mt-8 pt-6 border-t border-border"><h2 className="font-bold flex items-center gap-2 text-fuchsia-400 mb-1"><FaCode/> Kelola Developer</h2><p className="text-xs text-gray-500 mb-3">Owner dapat memberikan atau mencabut role Developer. Developer dianggap privileged seperti Admin.</p>{error&&<p className="text-xs text-red-400 mb-2">{error}</p>}<form onSubmit={add} className="flex gap-2 mb-3"><input value={login} onChange={e=>setLogin(e.target.value)} placeholder="Username GitHub..." className="flex-1 bg-panel border border-border rounded-lg px-3 py-2 text-xs outline-none focus:border-accent"/><button disabled={busy||!login.trim()} className="shrink-0 bg-accent text-black text-xs font-medium px-3 py-2 rounded-lg flex items-center gap-1.5 disabled:opacity-50"><FaPlus size={10}/> Tambah</button></form><div className="space-y-2">{rows.map(x=><div key={x.login} className="flex items-center justify-between gap-3 rounded-xl border border-border bg-panel p-3"><div><p className="text-sm font-medium">{x.login}</p><p className="text-[11px] text-gray-500">Ditambah oleh {x.added_by} · {new Date(x.created_at).toLocaleDateString("id-ID")}</p></div><button onClick={()=>remove(x.login)} disabled={busy} className="p-2 text-gray-400 hover:text-red-400"><FaTrash size={13}/></button></div>)}</div></div>}
